[build]
dir = "build"
generator = "Ninja"

[windows]
generator = "Visual Studio 16 2019"

[unix]
cc = "clang"
cxx = "clang++"
generator = "Unix Makefiles"

[format]
glob = ["src/**/*.cpp", "src/**/*.hpp", "include/**/*.hpp"]

[vcpkg]
enable = true
