[build]
dir = "build"
generator = "Ninja"

[unix]
cc = "clang"
cxx = "clang++"
generator = "Unix Makefiles"

[format]
glob = ["src/**/*.cpp", "include/**/*.hpp"]
# style = "Google"
# exclude = ["include/head.h"]

[vcpkg]
enable = true
