[build]
dir = "build"
generator = "Ninja"

[unix]
cc = "clang"
cxx = "clang++"
generator = "Unix Makefiles"

[format]
style = "LLVM"
glob = ["src/**/*.cpp", "include/**/*.hpp"]

[vcpkg]
enable = true
